-- GENERATED by tools/atlas_pack.lua — do not hand-edit.
return {
  ["chaser_1"] = { x = 0, y = 0, w = 24, h = 24, ox = 2, oy = 2 },
  ["chaser_2"] = { x = 26, y = 0, w = 24, h = 24, ox = 2, oy = 2 },
  ["gem_1"] = { x = 52, y = 0, w = 18, h = 18, ox = 3, oy = 3 },
  ["gem_2"] = { x = 0, y = 26, w = 18, h = 18, ox = 3, oy = 3 },
  ["gem_3"] = { x = 26, y = 26, w = 18, h = 18, ox = 3, oy = 3 },
  ["gem_4"] = { x = 52, y = 26, w = 18, h = 18, ox = 3, oy = 3 },
  ["player_1"] = { x = 0, y = 52, w = 26, h = 26, ox = 3, oy = 3 },
}
