-- Atlas packer: alpha-bounds trim + grid composition + generated layout
-- (layout files are BUILD OUTPUT — never hand-edit them; the intent manifest
-- is the hand-authored half). Trim offsets are recorded per frame because
-- AI-generated canvases carry padding ("trim jitter is universal").
-- Requires the LÖVE runtime for ImageData/Canvas; trim math is pure.

local atlas_pack = {}

-- pure: the smallest sub-rectangle of fully non-transparent pixels
-- returns x, y, w, h (or the full frame when everything is transparent)
function atlas_pack.trimBounds(imageData)
  local w, h = imageData:getWidth(), imageData:getHeight()
  local minX, minY, maxX, maxY = w, h, -1, -1
  for y = 0, h - 1 do
    for x = 0, w - 1 do
      local _, _, _, a = imageData:getPixel(x, y)
      if a > 0 then
        if x < minX then minX = x end
        if x > maxX then maxX = x end
        if y < minY then minY = y end
        if y > maxY then maxY = y end
      end
    end
  end
  if maxX < 0 then return 0, 0, w, h end
  return minX, minY, maxX - minX + 1, maxY - minY + 1
end

-- sources: { name = ImageData } ; pads frames into a fixed-width grid
-- returns { image = Canvas, layout = { name = { x, y, w, h, ox, oy } } }
-- layout ox/oy are the trim offsets: draw the frame at (x - ox) to restore
-- its original alignment (feet anchors survive trimming).
function atlas_pack.pack(sources, opts)
  opts = opts or {}
  assert(love and love.graphics, "atlas_pack.pack needs the LÖVE runtime")

  local trimmed = {}
  local maxW, maxH = 0, 0
  local order = {}
  for name in pairs(sources) do order[#order + 1] = name end
  table.sort(order) -- deterministic layout regardless of pairs order

  for _, name in ipairs(order) do
    local data = sources[name]
    local tx, ty, tw, th = atlas_pack.trimBounds(data)
    trimmed[#trimmed + 1] = { name = name, data = data, x = tx, y = ty, w = tw, h = th }
    if tw > maxW then maxW = tw end
    if th > maxH then maxH = th end
  end

  local columns = opts.columns or math.ceil(math.sqrt(#trimmed))
  local rows = math.ceil(#trimmed / columns)
  local cellW, cellH = maxW, maxH
  local width, height = columns * cellW, rows * cellH

  local canvas = love.graphics.newCanvas(math.max(width, 1), math.max(height, 1))
  love.graphics.setCanvas(canvas)
  love.graphics.clear(0, 0, 0, 0)
  love.graphics.setColor(1, 1, 1, 1)
  local layout = {}
  for i, frame in ipairs(trimmed) do
    local col = (i - 1) % columns
    local row = math.floor((i - 1) / columns)
    local x, y = col * cellW, row * cellH
    -- crop to the trim box BEFORE drawing: the layout quad (x, y, w, h) must
    -- hold exactly the trimmed pixels — drawing the full frame here would
    -- leave the content shifted by (ox, oy) inside the cell and quads would
    -- sample padding plus a corner of the art
    local cropped = love.image.newImageData(frame.w, frame.h)
    cropped:paste(frame.data, 0, 0, frame.x, frame.y, frame.w, frame.h)
    love.graphics.draw(love.graphics.newImage(cropped), x, y)
    layout[frame.name] = {
      x = x, y = y, w = frame.w, h = frame.h,
      ox = frame.x, oy = frame.y,      -- where the trim box sat in the source frame
      column = col + 1, row = row + 1, -- atlas page position
    }
  end
  love.graphics.setCanvas()
  return { image = canvas, layout = layout, width = width, height = height }
end

-- the generated layout file (build output)
function atlas_pack.layoutSource(layout)
  local out = { "-- GENERATED by tools/atlas_pack.lua — do not hand-edit.", "return {" }
  local names = {}
  for name in pairs(layout) do names[#names + 1] = name end
  table.sort(names)
  for _, name in ipairs(names) do
    local f = layout[name]
    out[#out + 1] = string.format(
      '  ["%s"] = { x = %d, y = %d, w = %d, h = %d, ox = %d, oy = %d },',
      name, f.x, f.y, f.w, f.h, f.ox, f.oy)
  end
  out[#out + 1] = "}"
  return table.concat(out, "\n") .. "\n"
end

return atlas_pack
